---
abstract: 'transaction and concurrency manager of cache systems.'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  Cache::Memcached::Fast: 0
  ExtUtils::MakeMaker: 6.42
  File::Which: 0
  Proc::Guard: 0
  Test::More: 0
  Test::Skip::UnlessExistsExecutable: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-Isolator
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Lite: 0
  List::Util: 0
  Time::HiRes: 0
  Try::Tiny: 0.09
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/Cache-Isolator.git
version: 0.02
